# Generated by Django 4.0.1 on 2022-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('body', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='blogimages/')),
            ],
        ),
    ]
